name = "cfw-image-worker"
main = "cfw_image.js"
compatibility_date = "2026-04-21"

[[r2_buckets]]
binding = "R2"
bucket_name = "cfw-image"

[[d1_databases]]
binding = "DB"
database_name = "cfw-image"
migrations_dir = "migrations"
